server:
  port : 8080

spring:
  application:
    name: Webdiet
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/diet-app
    username: ENC(OTidiAMB031F9m0ewHuPfq5wbWOUVLeLlgI3iAEXx6we8ZBYJiNjj6rPCIkaU9Az)
    password: ENC(N90HXsbb63uF2FebcINdegy6tueoHqLFeiPhUNS11vG867rNoPUPR1KKKLtlPAJK)

logging:
  file:
    path: ./logs
