server:
  port : 8080

spring:
  application:
    name: Webdiet
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/diet-app
    username: ENC(GTlhg4xDD/TmdE7hqXL2yWhtJ6Ap6agV1wdynnGo+QE5k5lMUE1zs0tD/PztoOFg)
    password: ENC(VRUG5O+2JwNQlSXvXqGVsb5Ro/1D6ab4EmOSYzrawoq2K8rvWxeWLe2Q2pLfUIUX)
    driverClassName: org.postgresql.Driver

logging:
  file:
    path: ./logs
